### ISSUE TITLE
Get and Set TimeofDay()

### ISSUE THREAD

**Issue by ClashofCraft972** [niknal357/sm-docu#1]
There is 2 you didn't put in scrapmechanicdocs.com : 

sm.game.GetTimeOfDay()
 - Return the Time of the Day (from 0 to 1)

sm.gale.SetTimeOfDay(Time)
Set the time of the day
 - Time : Int, set the time (from 0 to 1)

**Comment by niknal357** [comment]
https://scrapmechanicdocs.com/docs/Game-Script-Environment/Static-Functions/sm.game#gettimeofday
https://scrapmechanicdocs.com/docs/Game-Script-Environment/Static-Functions/sm.game#settimeofday
they do exist
